# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-06 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=b'')),
                ('nombre_de_la_mascota', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=200)),
            ],
        ),
    ]
